name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build Project
        run: swift build -v